// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_pxyWg8Qzj7ONeY16a9Axjon83ocybYE',
    appId: '1:521525963267:web:534b09eb4e4be5fc9b3c36',
    messagingSenderId: '521525963267',
    projectId: 'practica-movil-1',
    authDomain: 'practica-movil-1.firebaseapp.com',
    storageBucket: 'practica-movil-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3sQ0kkfHBh7YHSKwYzkHZwaA9mqLbAl8',
    appId: '1:521525963267:android:33030ab9b37ca4fd9b3c36',
    messagingSenderId: '521525963267',
    projectId: 'practica-movil-1',
    storageBucket: 'practica-movil-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJZte5VjHYDkGHNudkESCLAuTc2upC8T4',
    appId: '1:521525963267:ios:55c3d84f365ec9859b3c36',
    messagingSenderId: '521525963267',
    projectId: 'practica-movil-1',
    storageBucket: 'practica-movil-1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJZte5VjHYDkGHNudkESCLAuTc2upC8T4',
    appId: '1:521525963267:ios:55c3d84f365ec9859b3c36',
    messagingSenderId: '521525963267',
    projectId: 'practica-movil-1',
    storageBucket: 'practica-movil-1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_pxyWg8Qzj7ONeY16a9Axjon83ocybYE',
    appId: '1:521525963267:web:0d6b576bb532299e9b3c36',
    messagingSenderId: '521525963267',
    projectId: 'practica-movil-1',
    authDomain: 'practica-movil-1.firebaseapp.com',
    storageBucket: 'practica-movil-1.firebasestorage.app',
  );
}
